// will display all the spend rows
// import the things that i need
import React, { Component } from "react";
import { connect } from "react-redux";
import * as actions from "../actions/actions";
import AllSpendDisplay from "../components/AllSpendDisplay.jsx";

const mapStateToProps = (state) => ({
  // pass in the state that will be prop drilled
  description: state.spend.description,
  amount: state.spend.amount,
  // this should be auto generated by the database...
  type: state.spend.type,
});

const mapDispatchToProps = (dispatch) => ({
  addDescription: (description) =>
    dispatch(actions.addDescription(description)),
  addSpend: (amount) => dispatch(actions.addSpend(amount)),
  addType: (type) => dispatch(actions.addType(type)),
});

class SpendDisplayBox extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div className="spendbox">
        <h4>Inside of Spend Display</h4>
        <AllSpendDisplay
          addDescription={this.props.addDescription}
          description={this.props.description}
          addSpend={this.props.addSpend}
          amount={this.props.amount}
          addType={this.props.addType}
          type={this.props.type}
        />
      </div>
    );
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(SpendDisplayBox);
