// will display all the spend rows
// import the things that i need
import React, { Component } from "react";
import { connect } from "react-redux";
import * as actions from "../actions/actions";
import AllSpendDisplay from "../components/AllSpendDisplay.jsx";

const mapStateToProps = (state) => ({
  // pass in the state that will be prop drilled
  description: state.spend.description,
  amount: state.spend.amount,
  // this should be auto generated by the database...
  type: state.spend.type,
  date: state.spend.date,
});

const mapDispatchToProps = (dispatch) => ({
  addDescription: (description) =>
    dispatch(actions.addDescription(description)),
  addSpend: (amount) => dispatch(actions.addSpend(amount)),
  addType: (type) => dispatch(actions.addType(type)),
  addDate: (date) => dispatch(actions.addDate(date)),
});

class SpendDisplayBox extends Component {
  constructor(props) {
    super(props);
    this.state = {
      values: [],
    };
    this.getFetch = this.getFetch.bind(this);
  }

  getFetch() {
    fetch("/spend", {
      method: "GET",
      headers: { "content-type": "application/json" },
    })
      .then((data) => data.json())
      .then((json) => {
        this.setState({ values: json });
        console.log("json values: ", this.state.values);
      })
      .catch((err) => console.error(err));
  }

  componentDidMount() {
    this.getFetch();
  }

  render() {
    return (
      <div className="spendbox">
        <h4>Inside of Spend Display</h4>
        <AllSpendDisplay
          addDescription={this.props.addDescription}
          description={this.props.description}
          addSpend={this.props.addSpend}
          amount={this.props.amount}
          addType={this.props.addType}
          type={this.props.type}
          addDate={this.props.addDate}
          date={this.props.date}
          getFetch={this.getFetch}
          fetchState={this.state.values}
        />
      </div>
    );
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(SpendDisplayBox);
